version: '3'

services:
#  app:
#    build: .
#    volumes:
#      - .:/app:cached
#    ports:
#      - 8000:8000
#    command: ["wait-for", "db:3306", "--", "air"]
#    depends_on:
#      - db
#      - redis
  db:
    image: mariadb:focal
    environment:
      - MYSQL_ROOT_PASSWORD=bjbest
      - MYSQL_DATABASE=kry
    ports:
      - 3306:3306